### ISSUE TITLE
Keyword completion (^N^P) E486 Pattern not found

### ISSUE THREAD

**Issue by wolandark** [ackyshake/VimCompletesMe#78] opened 2022-08-22 00:58 UTC
Hello and hope you are well.
vcm has stopped working since vim9. I use it with coc.nvim and it was working perfectly fine before but now on a fresh installation of vim and the plugins it returns the error in the title. I must also point out that I have vcm on two another devices and having upgraded to vim9 hasn't caused any problems and since I've tested it out on multiple fresh installs of Arch with different kernels (just in case) I can confirm that the issue only exists in fresh installs of vim and vcm. My workflow is quite dependent on vcm so any help would be extremely appreciated. The error also appears when using other Tab completion plugins such as super tab so its not just vcm and possibly something bigger in vim9. verbose imap <tab> returns as expected with the latest mapping belonging to vcm. 
Thank you very much and please tell me if I should provide any additional info.

**Comment by ackyshake** [comment] 2022-08-24 00:32
Hmm, you shouldn't have any issues running VCM on vim9. I'm running it just fine on my setup (I currently have vim9 patches 1-40). 

Can you show what `:verbose imap <Tab>` shows for you?

Another thing to try is to run without any other plugins to see if that works.

**Comment by wolandark** [comment] 2022-08-25 01:12
Certainly!

i  <Tab>         <Plug>vim_completes_me_forward
        Last set from ~/.vim/plugged/VimCompletesMe/plugin/VimCompletesMe.vim line 30
Press ENTER or type command to continue
```
I've also tried it with no other plugin except for coc since thats my completion engine and the issue persists.

**Comment by ackyshake** [comment] 2022-08-25 23:10
Just so I can try to reproduce your setup, what specific Vim version are you running?

It would also be great if you could just try it with VCM to see if it works, and exclude coc.nvim.

**Comment by wolandark** [comment] 2022-08-29 02:49
Hello again. Excuse me for this very late reply, I had an issue and couldn't access github properly

This is my entire vim --version output where the issue happens
[https://github.com/wolandark/vimbug/blob/main/vim%20on%20ryzen.jpg](url)

I also made this short video to demonstrate the behavior. You can see that tab completion sometimes works and sometimes doesn't.
[https://github.com/wolandark/vimbug/blob/main/faulty%20vim.gif](url)

This is the vim --version where the issue doesn't happen and also a gif to demonstrate the correct behavior.
[https://github.com/wolandark/vimbug/blob/main/correctvim.png](url)

[https://github.com/wolandark/vimbug/blob/main/sorrectvim.gif](url)

It just happens that I was installing freebsd for a client and I grabbed my vimrc from [https://github.com/wolandark/wim](url)
and everything was working fine.

thank you for your time.

**Comment by ackyshake** [comment] 2022-08-29 03:29
Thanks for the detailed information!

Here's what I tried from my side:

1. Vim version 9.0 with patches 1-246 (which matches your version)
2. VimCompletesMe placed in ~/.vim/pack/my/start/VimCompletesMe.vim
3. ~/.vimrc with just two lines: "syntax on" and "filetype plugin indent on"

Here is what I see:

![vcm-debug-issue-74](https://user-images.githubusercontent.com/1159146/187116960-9fb30910-81a9-416e-b2ee-563ca9088e69.gif)

As I cannot reproduce with a minimal setup, I am going to close this issue. 

The only difference I see if that you have some additional completion plugins that might interfere with VCM functionality. I suggest reproducing this issue as closely as possible to my setup above. No other plugins should be enabled when you try to reproduce.

If you discover that you can reproduce this issue with VCM + some other plugin, I would then suggest disabling `g:vcm_default_maps` (See `:help g:vcm_default_maps`) and referring to FAQ number 3 under `:help VimCompletesMe-faq`. Apologies if I can't help more, but it's quite difficult trying to make VCM play nice with all plugins out there that map `<Tab>` and `<Shift-Tab>`, as you can imagine. Since you mentioned that Supertab also has this issue, I surmise that it is some other plugin in your toolbox that is causing this issue and this is not a VCM issue.

**Closed by ackyshake** 2022-08-29 03:29 UTC
